### ISSUE TITLE
Update the entry in crates.io

### ISSUE THREAD

**Issue by achan1989** [astro/stm32-eth#2]
It would be good to update https://crates.io/crates/stm32-eth with links to this repository and some generated documentation.  I almost passed over this crate because I thought it was junk/abandoned.

**Comment by astro** [comment]
You're right. I'm just waiting for https://github.com/m-labs/smoltcp/issues/259 to release a new version.

**Comment by whitequark** [comment]
Released

**Comment by astro** [comment]
Fixed in bfeddc8
